name: cfpb_complaints
version: 0.1.0
config-version: 2

profile: cfpb_complaints

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

clean-targets:
  - target
  - dbt_packages

models:
  cfpb_complaints:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
